// <auto-generated />
using System;
using DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataBase.Migrations
{
    [DbContext(typeof(PriazovContext))]
    partial class PriazovContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataBase.Models.Industry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Industries");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Образовательное учреждение"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Научно-исследовательский институт"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Научно-образовательный проект"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Государственное учреждение"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Компания, ведущая коммерческую деятельность"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Стартап"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Финансовый инструмент (банк, фонд и другие)"
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Акселератор/инкубатор/технопарк"
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Ассоциация/объединение"
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Инициатива"
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Отраслевое событие/научная конференция"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Другое"
                        });
                });

            modelBuilder.Entity("DataBase.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("IndustryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RegionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IndustryId");

                    b.HasIndex("RegionId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DataBase.Models.Region", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Краснодарский край"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Ростовская область"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "ЛНР"
                        },
                        new
                        {
                            Id = 4L,
                            Name = "ДНР"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Херсонская область"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Запорожская область"
                        });
                });

            modelBuilder.Entity("DataBase.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsManager")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");

                    b.HasAlternateKey("Phone");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DataBase.Models.UserProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("DataBase.Models.Project", b =>
                {
                    b.HasOne("DataBase.Models.Industry", "Industry")
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBase.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industry");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("DataBase.Models.UserProject", b =>
                {
                    b.HasOne("DataBase.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("DataBase.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
